### ISSUE TITLE
这个我来吧！

### ISSUE THREAD

**Issue by CodeAlmas** [thstack/anne#1]
日记本我来??

**Comment by hajifish** [comment]
先到先得，You got it first right now....

------------------ Original ------------------

**Comment by CodeAlmas** [comment]
okay

**Comment by hajifish** [comment]
那就longeek 来做， frazy 就搞定 ashinamo 明天能搞定吗？

------------------ Original ------------------

**Comment by longgeek** [comment]
@frazy 来做吧，我这边还有三个题型。

**Comment by frazy** [comment]
hello，为什么把我拉进来？ 是否弄错了

**Comment by baoyiluo** [comment]
是搞错了 @frazy

**Comment by baoyiluo** [comment]
只能搞定后台今天
